[package]
name = "st7789"
version = "0.1.0"
edition = "2021"

[lib]
bench = false
doctest = false
test = false

[dependencies]
display-interface = { workspace = true }
embedded-hal = { workspace = true }
