[workspace]
members = [
    "lsusb"
]

resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.86" }
env_logger = { version = "0.11.3" }
log = { version = "0.4.21" }
nusb = { version = "0.1.9" }
